# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 15:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trello_app', '0004_auto_20170402_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='boards',
        ),
        migrations.RemoveField(
            model_name='board',
            name='child',
        ),
        migrations.RemoveField(
            model_name='card',
            name='lists',
        ),
        migrations.AddField(
            model_name='card',
            name='boards',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='trello_app.Board'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='mylist',
            field=models.CharField(default='todo', max_length=25),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='List',
        ),
    ]
